- name: 'Install Linux tools'
  hosts: server
  become: yes
  tasks:
    - name: "Install multiple Packages"
      apt:
        update_cache: yes
      apt: 
        name: '{{ item }}'
        state: present
      with_items:
        - tmux
        - net-tools 
        - unzip
        - zip
        - nmap
        - software-properties-common
        - ansible

