- name: 'Update the apt package index and install packages to allow apt to use a repository over HTTPS'
  apt: 
    name: '{{ item }}' 
    state: present 
    update_cache: yes
  with_items:
    - apt-transport-https 
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: 'Add Docker’s official GPG key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: 'Return Ubuntu Distribtion'
  command: lsb_release -cs
  register: release

- name: 'Command to set up the stable repository'
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line:  'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable'
    create: yes
      
- name: 'Install the latest version of Docker Engine and containerd'
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items: 
    - docker-ce='{{ dockerversion }}'
    - docker-ce-cli='{{ dockerversion }}'
    - containerd.io
- name: 'Install docker compose'  
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ composeversion }}/docker-compose-Linux-x86_64'
    dest: /usr/local/bin/docker-compose
    mode: '0744'
- name: 'Create Symbolic link for docker compose'
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link


